version: '3'

services:
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=superpass
      - MYSQL_DATABASE=blueprint
      - MYSQL_USER=blue_user
      - MYSQL_PASSWORD=blue_pass

  web:
    build: .
    command: python blueprint/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
