version: '3'

services:
  db:
    image: mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=blueprint
      - MYSQL_USER=blueprint
      - MYSQL_PASSWORD=blueprint

  web:
    build: .
    command: python blueprint/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
